name: Docker Build CI

on:
  push:
    branches:
      - develop
      - master
    tags:
      - 'prod-*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set GHCR image path
        run: echo "GHCR_REPO=${REGISTRY}/${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Extract prod tag
        if: startsWith(github.ref, 'refs/tags/prod-')
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          yq eval ".image.tag = \"${TAG_NAME}\"" -i kubernetes/prod/values.yaml

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME_RKM4BC }}
          password: ${{ secrets.GHCR_PAT_RKM4BC }}

      - name: Build & Push (develop/feature)
        if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/prod-')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.GHCR_REPO }}:${{ github.ref_name }}

      - name: Build & Push (master)
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GHCR_REPO }}:master
            ${{ env.GHCR_REPO }}:latest

      - name: Build & Push (prod)
        if: startsWith(github.ref, 'refs/tags/prod-')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.GHCR_REPO }}:${{ env.TAG_NAME }}

      - name: Commit Helm tag update
        if: s
